# Generated by Django 4.1.5 on 2023-01-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BestllteArtikel',
            new_name='BestellteArtikel',
        ),
    ]
